/*
389. Find the Difference

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.


Example 1:
  Input: s = "abcd", t = "abcde"
  Output: "e"
  Explanation: 'e' is the letter that was added.
Example 2:
  Input: s = "", t = "y"
  Output: "y"
 

Constraints:
  0 <= s.length <= 1000
  t.length == s.length + 1
  s and t consist of lowercase English letters.
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function (s, t) {
  const hashMap = {};

  for (let item of s) {
    hashMap[item] = (hashMap?.[item] || 0) + 1;
  }

  for (let item of t) {
    if (!hashMap[item]) return item;
    else hashMap[item]--;
  }
};
